PlanIt-----PMS-Project/src/Web/PlanIt.Web/Areas/Client/Controllers/ClientsController.cs
namespace PlanIt.Web.Areas.Client.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PlanIt.Common;
    using PlanIt.Web.Controllers;

    [Authorize(Roles = GlobalConstants.ClientRoleName)]
    [Area("Client")]
    public class ClientsController : BaseController
    {
    }
}

PlanIt-----PMS-Project/src/Web/PlanIt.Web/Controllers/AddCostsController.cs
namespace PlanIt.Web.Controllers
{
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PlanIt.Common;
    using PlanIt.Data.Models;
    using PlanIt.Services.Data;
    using PlanIt.Web.Infrastructure.Filters;
    using PlanIt.Web.ViewModels.AdditionalCosts;
    using PlanIt.Web.ViewModels.AdditionalCosts.Projects;
    using PlanIt.Web.ViewModels.AdditionalCosts.SubProjects;

    [Authorize]
    [TypeFilter(typeof(MyProjectsOnlyAttribute))]
    public class AddCostsController : BaseController
    {
        private readonly UserManager<PlanItUser> userManager;
        private readonly IAdditionalCostsService additionalCostsService;
        private readonly IProjectsService projectsService;
        private readonly ISubProjectsService subProjectsService;

        public AddCostsController(
            UserManager<PlanItUser> userManager,
            IAdditionalCostsService additionalCostsService,
            IProjectsService projectsService,
            ISubProjectsService subProjectsService)
        {
            this.userManager = userManager;
            this.additionalCostsService = additionalCostsService;
            this.projectsService = projectsService;
            this.subProjectsService = subProjectsService;
        }

        public async Task<IActionResult> AddToSubProject(int? id)
        {
            var projects = await this.GetProjects(this.User);
            this.ViewData["Projects"] = projects;

            if (id == null)
            {
                return this.View();
            }

            var projectId = (int)id;
            var selectedProject = await this.projectsService
                .GetByIdAsync<AddCostAddToSubProjectProjectViewModel>(projectId);

            this.ViewData["Project"] = selectedProject;

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddToSubProject(AddCostAddToSubProjectInputModel inputModel)
        {
            if (inputModel.SubProjectId == null)
            {
                this.ModelState.AddModelError(string.Empty, "Project part doesn`t exist!");
            }

            var selectedProject = await this.projectsService
                    .GetByIdAsync<AddCostAddToSubProjectProjectViewModel>(inputModel.ProjectId);

            if (selectedProject == null)
            {
                this.ModelState.AddModelError(string.Empty, "Project doesn`t exist!");
            }

            if (!this.ModelState.IsValid)
            {
                var projects = await this.GetProjects(this.User);

                this.ViewData["Projects"] = projects;
                this.ViewData["Project"] = selectedProject;

                return this.View(inputModel);
            }

            await this.additionalCostsService.AddAsync<AddCostAddToSubProjectInputModel>(inputModel);

            return this.RedirectToAction(nameof(this.CostsBySubProject), new { subProjectId = inputModel.SubProjectId });
        }

        public async Task<IActionResult> AddToProject()
        {
            var projects = await this.GetProjects(this.User);
            this.ViewData["Projects"] = projects;

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddToProject(AddCostAddToProjectInputModel inputModel)
        {
            var project = await this.projectsService
                    .GetByIdAsync<AddCostAddToProjectProjectViewModel>(inputModel.ProjectId);

            if (project == null)
            {
                this.ModelState.AddModelError(string.Empty, "Project doesn`t exist!");
            }

            if (!this.ModelState.IsValid)
            {
                var projects = await this.GetProjects(this.User);

                this.ViewData["Projects"] = projects;

                return this.View(inputModel);
            }

            await this.additionalCostsService.AddAsync<AddCostAddToProjectInputModel>(inputModel);

            return this.RedirectToAction(nameof(this.CostsByProject), new { projectId = project.Id });
        }

        public async Task<IActionResult> CostsByProject(int projectId)
        {
            var project = await this.projectsService
                .GetByIdAsync<AddCostCostsByProjectProjectViewModel>(projectId);

            if (project == null)
            {
                return this.NotFound();
            }

            return this.View(project);
        }

        public async Task<IActionResult> CostsBySubProject(int subProjectId)
        {
            var subProject = await this.subProjectsService
                .GetByIdAsync<AddCostCostsBySubProjectSubProjectViewModel>(subProjectId);

            var project = await this.projectsService.GetByIdAsync(subProject.ProjectId);

            if (subProject == null || project == null)
            {
                return this.NotFound();
            }

            return this.View(subProject);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var cost = await this.additionalCostsService.GetByIdAsync<AddCostEditInputModel>(id);

            if (cost == null)
            {
                return this.NotFound();
            }

            return this.View(cost);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AddCostEditInputModel inputModel)
        {
            if (id != inputModel.Id)
            {
                return this.NotFound();
            }

            var cost = await this.additionalCostsService
                .GetByIdAsync<AddCostViewModel>(inputModel.Id);

            if (cost == null)
            {
                return this.NotFound();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            await this.additionalCostsService.EditAsync<AddCostEditInputModel>(inputModel);

            return this.RedirectToAction(nameof(this.CostsByProject), new { projectId = cost.ProjectId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var cost = await this.additionalCostsService
                .GetByIdAsync<AddCostDeleteViewModel>(id);

            if (cost == null)
            {
                return this.NotFound();
            }

            await this.additionalCostsService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.CostsByProject), new { projectId = cost.ProjectId });
        }

        private async Task<IEnumerable<AddCostSelectProjectViewModel>> GetProjects(ClaimsPrincipal principal)
        {
            var currentUserId = this.userManager.GetUserId(principal);

            var projects = new List<AddCostSelectProjectViewModel>();

            if (principal.IsInRole(GlobalConstants.UserRoleName))
            {
                projects = (List<AddCostSelectProjectViewModel>)await this.projectsService
                .GetAllByManagerIdAsync<AddCostSelectProjectViewModel>(currentUserId);
            }
            else
            {
                projects = (List<AddCostSelectProjectViewModel>)await this.projectsService
               .GetAllAsync<AddCostSelectProjectViewModel>();
            }

            return projects;
        }
    }
}

PlanIt-----PMS-Project/src/Web/PlanIt.Web/Controllers/TasksController.cs
namespace PlanIt.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PlanIt.Common;
    using PlanIt.Data.Models;
    using PlanIt.Services.Data;
    using PlanIt.Web.Infrastructure.Filters;
    using PlanIt.Web.ViewModels.Tasks;
    using PlanIt.Web.ViewModels.Tasks.ProgressStatuses;
    using PlanIt.Web.ViewModels.Tasks.Projects;
    using PlanIt.Web.ViewModels.Tasks.SubProjects;

    [Authorize]
    public class TasksController : BaseController
    {
        private readonly UserManager<PlanItUser> userManager;
        private readonly RoleManager<PlanItRole> roleManager;
        private readonly IProjectsService projectsService;
        private readonly ISubProjectsService subProjectsService;
        private readonly IProblemsService problemsService;
        private readonly IHoursService hoursService;
        private readonly IProgressStatusesService progressStatusesService;

        public TasksController(
            UserManager<PlanItUser> userManager,
            RoleManager<PlanItRole> roleManager,
            IProjectsService projectsService,
            ISubProjectsService subProjectsService,
            IProblemsService problemsService,
            IHoursService hoursService,
            IProgressStatusesService progressStatusesService)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.projectsService = projectsService;
            this.subProjectsService = subProjectsService;
            this.problemsService = problemsService;
            this.hoursService = hoursService;
            this.progressStatusesService = progressStatusesService;
        }

        [TypeFilter(typeof(MyProjectsOnlyAttribute))]
        public async Task<IActionResult> Index()
        {
            var problems = Enumerable.Empty<TaskIndexViewModel>();

            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var currentUserId = this.userManager.GetUserId(this.User);

                problems = await this.problemsService.GetAllByManagerIdAsync<TaskIndexViewModel>(currentUserId);
            }
            else
            {
                problems = await this.problemsService.GetAllAsync<TaskIndexViewModel>();
            }

            return this.View(problems);
        }

        [TypeFilter(typeof(MyProjectsOnlyAttribute))]
        public async Task<IActionResult> TaskHours(int id)
        {
            var problem = await this.problemsService.GetByIdAsync<TaskTaskHoursViewModel>(id);

            if (problem == null)
            {
                return this.NotFound();
            }

            return this.View(problem);
        }

        public async Task<IActionResult> MyTasks()
        {
            var currentUserId = this.userManager.GetUserId(this.User);

            var problems = await this.problemsService
                .GetAllByUserIdAsync<TaskMyTaskViewModel>(currentUserId);

            return this.View(problems);
        }

        public async Task<IActionResult> MyTaskHours(int id)
        {
            var problem = await this.problemsService
                .GetByIdAsync<TaskMyTaskHoursViewModel>(id);

            if (problem == null)
            {
                return this.NotFound();
            }

            var currentUserId = this.userManager.GetUserId(this.User);

            problem.Hours = problem.Hours.Where(h => h.UserId == currentUserId);

            return this.View(problem);
        }

        [TypeFilter(typeof(MyProjectsOnlyAttribute))]
        public async Task<IActionResult> Assign(int? id)
        {
            var projects = await this.GetProjects(this.User);
            this.ViewData["Projects"] = projects;

            if (id == null)
            {
                return this.View();
            }

            var projectId = (int)id;
            var selectedProject = await this.projectsService
                .GetByIdAsync<TaskAssignProjectViewModel>(projectId);
            var selectUsers = await this.SelectUsersAsync(this.User);

            this.ViewData["Project"] = selectedProject;
            this.ViewData["Users"] = selectUsers;

            return this.View();
        }

        [HttpPost]
        [TypeFilter(typeof(MyProjectsOnlyAttribute))]
        public async Task<IActionResult> Assign(TaskAssignInputModel inputModel)
        {
            var subProject = await this.subProjectsService
                .GetByIdAsync<TaskAssignSubProjectViewModel>(inputModel.SubProjectId);

            if (subProject == null)
            {
                this.ModelState.AddModelError(string.Empty, "Project part doesn`t exist!");
            }

            var user = await this.userManager.FindByIdAsync(inputModel.UserId);

            if (user == null)
            {
                this.ModelState.AddModelError(string.Empty, "User is not assigned!");
            }

            var selectedProject = await this.projectsService
                    .GetByIdAsync<TaskAssignProjectViewModel>(inputModel.ProjectId);

            if (selectedProject == null)
            {
                this.ModelState.AddModelError(string.Empty, "Project doesn`t exist!");
            }

            if (inputModel.DueDate != null)
            {
                if (inputModel.DueDate?.ToUniversalTime() > subProject.DueDate)
                {
                    this.ModelState.AddModelError(string.Empty, $"Due date has to be before project part Due date");
                }
            }

            if (!this.ModelState.IsValid)
            {
                var projects = await this.GetProjects(this.User);
                var selectUsers = await this.SelectUsersAsync(this.User);

                this.ViewData["Projects"] = projects;
                this.ViewData["Project"] = selectedProject;
                this.ViewData["Users"] = selectUsers;

                return this.View(inputModel);
            }

            await this.problemsService.AssignAsync<TaskAssignInputModel>(user, inputModel);

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpPost]
        public async Task<IActionResult> AddHours(int id, decimal hours)
        {
            var problem = await this.problemsService.GetByIdAsync(id);

            if (problem == null)
            {
                return this.NotFound();
            }

            if (hours <= 0)
            {
                return this.RedirectToAction(nameof(this.MyTasks));
            }

            var user = await this.userManager.GetUserAsync(this.User);

            await this.hoursService.AddHourAsync(problem, user, hours);
            await this.problemsService.AddHoursAsync(id, hours);

            return this.RedirectToAction(nameof(this.MyTasks));
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(int problemId, string status)
        {
            var problem = await this.problemsService.GetByIdAsync(problemId);

            if (problem == null)
            {
                return this.NotFound();
            }

            var progressStatus = await this.progressStatusesService.GetByNameAsync(status);

            if (progressStatus == null)
            {
                return this.NotFound();
            }

            await this.problemsService.ChangeStatusAsync(problemId, progressStatus);

            if (status == GlobalConstants.ProgressStatusCompleted)
            {
                var subProject = await this.subProjectsService.ChangeStatusAsync(problem.SubProjectId, progressStatus);

                if (subProject.ProgressStatus.Name == GlobalConstants.ProgressStatusCompleted)
                {
                    await this.projectsService.ChangeStatusAsync(subProject.ProjectId, progressStatus);
                }
            }

            return this.RedirectToAction(nameof(this.MyTasks));
        }

        [TypeFilter(typeof(MyProjectsOnlyAttribute))]
        public async Task<IActionResult> AddUser(int id)
        {
            var problem = await this.problemsService.GetByIdAsync<TaskAddUserInputModel>(id);

            if (problem == null)
            {
                return this.NotFound();
            }

            var selectUsers = await this.SelectUsersAsync(this.User);

            this.ViewData["Users"] = selectUsers;

            return this.View(problem);
        }

        [HttpPost]
        [TypeFilter(typeof(MyProjectsOnlyAttribute))]
        public async Task<IActionResult> AddUser(int id, TaskAddUserInputModel inputModel)
        {
            if (id != inputModel.Id)
            {
                this.ModelState.AddModelError(string.Empty, "Task doesn`t exist!!!");
            }

            var selectedUser = await this.userManager.FindByIdAsync(inputModel.UserId);

            if (selectedUser == null)
            {
                this.ModelState.AddModelError(string.Empty, "User doesn`t exist!!!");
            }

            if (!this.ModelState.IsValid)
            {
                var selectUsers = await this.SelectUsersAsync(this.User);

                this.ViewData["Users"] = selectUsers;

                return this.View(inputModel);
            }

            await this.problemsService.AddUserAsync(id, selectedUser);

            return this.RedirectToAction(nameof(this.Index));
        }

        [TypeFilter(typeof(MyProjectsOnlyAttribute))]
        public async Task<IActionResult> Edit(int id)
        {
            var problem = await this.problemsService.GetByIdAsync<TaskEditInputModel>(id);

            if (problem == null)
            {
                return this.NotFound();
            }

PlanIt-----PMS-Project/src/Web/PlanIt.Web/Views/Shared/_FooterPartial.cshtml
@using PlanIt.Common

<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        <vc:company-name></vc:company-name> Ltd.
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; @DateTime.Now.Year - @GlobalConstants.SystemName</strong> All rights reserved.
</footer>

PlanIt-----PMS-Project/src/Web/PlanIt.Web/Views/Shared/_IdentityStylesPartial.cshtml
<environment names="Development">
    <!-- Font Awesome Icons -->
    <link href="~/lib/animate/animate.css" rel="stylesheet" asp-append-version="true" />
</environment>
<environment names="Staging,Production">
    <!-- Font Awesome Icons -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet" asp-append-version="true" />
</environment>

PlanIt-----PMS-Project/src/Web/PlanIt.Web/Views/Shared/_ManagementDashboardPartial.cshtml
@using System.Globalization
@model PlanIt.Web.ViewModels.Dashboard.IndexManagementViewModel

<div class="content">
    <div class="container-fluid">
        <!-- Small boxes (Invites) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>@Model.AllProjectsCount</h3>
                        <p>Total Projects</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Projects"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>@Model.AllApprovedProjectsCount</h3>
                        <p>All approved projects</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-unlocked"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Clients"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>@Model.AllCompletedProjectsCount</h3>
                        <p>Total completed projects</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pricetag"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Projects"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>@Model.AssignedManagersCount</h3>
                        <p>All project managers</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-stalker"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Projects"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Small boxes -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>@Model.AssignedUsersCount</h3>
                        <p>Total users with tasks</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-person"></i>
                    </div>
                    <a asp-area=""
                       asp-controller="Tasks"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>@Model.FreeUsersCount</h3>
                        <p>Free users</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-person-outline"></i>
                    </div>
                    <a asp-area=""
                       asp-controller="Tasks"
                       asp-action="Assign"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>@Model.TotalBudgetApprovedProjects.ToString("F2", CultureInfo.InvariantCulture)</h3>
                        <p>Total approved budget</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-cash"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Projects"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>@Model.TotalBudgetCompletedProjects.ToString("F2", CultureInfo.InvariantCulture)</h3>
                        <p>Total completed budget</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-pricetag"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Projects"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Small boxes -->
        <div class="row">   
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>@Model.TotalCostsCompletedProjects.ToString("F2", CultureInfo.InvariantCulture)</h3>
                        <p>Total costs</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-calculator"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Projects"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>@Model.TotalProfit.ToString("F2", CultureInfo.InvariantCulture)</h3>
                        <p>Total profit</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-calculator-outline"></i>
                    </div>
                    <a asp-area="Management"
                       asp-controller="Projects"
                       asp-action="Index"
                       class="small-box-footer">
                        More info
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </div>
</div>

PlanIt-----PMS-Project/src/Web/PlanIt.Web/Views/Shared/_NavBarPartial.cshtml
@{
    var dateAndTime = DateTime.Now;
    var date = dateAndTime.Date.ToShortDateString();
    var dayOfWeek = dateAndTime.DayOfWeek;
}

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <div class="nav-link">@date - @dayOfWeek.</div>
        </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

PlanIt-----PMS-Project/src/Web/PlanIt.Web/Views/Shared/_SubProjectsMainSideBarPartial.cshtml
@using PlanIt.Web.ViewModels.Management.Projects
@using PlanIt.Data.Models
@using PlanIt.Common
@using PlanIt.Services.Data
@using Microsoft.AspNetCore.Identity

@inject UserManager<PlanItUser> userManager
@inject IProjectsService projectsService

@{
    var currentUserId = this.userManager.GetUserId(this.User);

    var projects = await this.projectsService.GetAllByManagerIdAsync<ProjectViewModel>(currentUserId);

    var hasAssignedProjects = false;

    if (projects.Count() > 0)
    {
        hasAssignedProjects = true;
    }
}

@if (hasAssignedProjects || this.User.IsInRole(GlobalConstants.ProjectManagerRoleName))
{
    <li class="nav-item has-treeview">
        <a href="#" class="nav-link">
            <i class="nav-icon fas fa-align-justify"></i>
            <p>
                Project parts
                <i class="right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a asp-area="" asp-controller="SubProjects" asp-action="Create" class="nav-link">
                    <i class="fas fa-indent nav-icon"></i>
                    <p>Create</p>
                </a>
            </li>
        </ul>
    </li>
    <li class="nav-item has-treeview">
        <a href="#" class="nav-link">
            <i class="nav-icon fas fa-money-check"></i>
            <p>
                Additional costs
                <i class="right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a asp-area="" asp-controller="AddCosts" asp-action="AddToProject" class="nav-link">
                    <i class="fas fa-coins nav-icon"></i>
                    <p>Add cost to project</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="AddCosts" asp-action="AddToSubProject" class="nav-link">
                    <i class="fas fa-coins nav-icon"></i>
                    <p>Add cost to project part</p>
                </a>
            </li>
        </ul>
    </li>
}
<li class="nav-item has-treeview">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-tasks"></i>
        <p>
            Tasks
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        @if (hasAssignedProjects || this.User.IsInRole(GlobalConstants.ProjectManagerRoleName))
        {
            <li class="nav-item">
                <a asp-area="" asp-controller="Tasks" asp-action="Index" class="nav-link">
                    <i class="fas fa-indent nav-icon"></i>
                    <p>All Tasks</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="Tasks" asp-action="Assign" class="nav-link">
                    <i class="fas fa-indent nav-icon"></i>
                    <p>Assign Task</p>
                </a>
            </li>            
        }
        <li class="nav-item">
            <a asp-area="" asp-controller="Tasks" asp-action="MyTasks" class="nav-link">
                <i class="fas fa-clone nav-icon"></i>
                <p>My Tasks</p>
            </a>
        </li>
    </ul>
</li>